### ISSUE TITLE
Not Working in Linux X64 - Python 3.10.4

### ISSUE THREAD

**Issue by prajwal-kesava** [adobe/aepp#9]
Hello Team,

I tried to use aepp in linux machine X64 (PY 3.10.4) of azure function app service plan. The "aepp" library is not working due to "[Error] ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)"

"aepp" is the root cause for this issue. Could you help me out whats wrong with installing in linux machine.
