### ISSUE TITLE
requirements pulling in an outdated pathlib module that causes issues with pip at and beyond python 3.10

### ISSUE THREAD

**Issue by timroster** [adobe/aepp#26]
### Expected Behaviour
`pip install aepp` on python 3.10 does not affect the behavior of subsequent pip installs

### Actual Behaviour
#9 also observed when using IBM spark 3.3 with python 3.10 runtime (but not with spark 3.3 with python 3.9)

### Reproduce Scenario (including but not limited to)
Observed in some python 3.10 environments, e.g. #9  and also in IBM watson studio runtimes with spark and python 3.10. Does not seem to be reproducible in every python 3.10 environment.

#### Steps to Reproduce
```
pip install aepp
pip install adlfs
...
Installing collected packages: pathlib, pathlib2, aepp
Successfully installed aepp-0.3.2.post1 pathlib-1.0.1 pathlib2-2.3.7.post1
Traceback (most recent call last):
  File "/home/spark/shared/conda/envs/python/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/opt/ibm/conda/miniconda/lib/python/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/ibm/conda/miniconda/lib/python/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/ibm/conda/miniconda/lib/python/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/opt/ibm/conda/miniconda/lib/python/site-packages/pip/_internal/build_env.py", line 6, in <module>
    import pathlib
  File "/opt/ibm/conda/miniconda/lib/python/site-packages/pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/opt/ibm/conda/miniconda/lib/python3.10/collections/__init__.py)
```
#### Platform and Version
The `pathlib.py` file that is added to site-packages when `pathlib-1.0.1` is installed by `aepp` tries to import **Sequence** from **collections** but this was deprecated in python 3.3 and has stopped working in 3.10.

### Recommended fix
Since there is a built-in version of `pathlib` available from version 3.4 on and the [pypi module](https://pypi.org/project/pathlib/) `pathlib-1.0.1` is just a backport of its features, it is suggested to drop the explicit references to `pathlib` and `pathlib2` in the requirements and setup for this library.

**Comment by pitchmuc** [comment]
Hello @timroster , 
I have a done a patch release yesterday and the new version : 0.3.2.post3 should not have this issue anymore.

**Comment by timroster** [comment]
@pitchmuc - yes, confirming the updates to drop `pathlib` as a requirement in 0.3.2.post3 has fixed the issue in watson studio runtime for spark 3.3 and python 3.10. I think it's reasonable to mark this as closed.
